### ISSUE TITLE
ANE not supports for iOS - library file not universal library

### ISSUE THREAD

**Issue by ukmunnithan** [juank-pa/JKLocalNotifications-ANE#1] opened 2017-06-02 10:55 UTC
When trying to add the ane in our project it is showing the error as 
Error: libLocalNotificationLib.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

**Comment by juank-pa** [comment] 2017-07-30 03:35
@ukmunnithan I actually stopped maintaining the ANE a long time ago. I resumed fixing it recently. When I tried to fix this issue a lot more appeared because of the changes in the way local notifications were handled in newer iOS versions. After some iterations, I have now a new version of the ANE. I'm just detailing a bit the documentation and other things but you can give it a try. From now, on I'm not uploading the compiled ANE anymore so that you can compile the ANE based on what you need (ios, ios simulator, android, etc). But if you need a compiled version for a device I can compile it for you.

**Comment by juank-pa** [comment] 2017-07-30 12:51
The fixed version is still in being worked on the PR I have not merged it yet.

**Closed as completed** 2017-08-02 05:58 UTC

**Comment by ukmunnithan** [comment] 2017-08-09 09:30
Thank you for the update..

Today I go through the ane and its working fine..

Thanks for your kind help


Is it possible to change the body part dynamically each day of the local notification??
For example I want to show each date in local notification body by each day.. Any help?

**Comment by juank-pa** [comment] 2017-08-15 16:42
I don't think it is possible because once the notification is stored you cannot modify the message. The only thing I can think of is storing many different notifications one for each day with a different message.

**Comment by ukmunnithan** [comment] 2017-09-01 09:48
Hello,

The notification is not displaying if the app is in foreground state..
If the app in in background or killed state its showing.. Is there a way to display if it is in foreground

**Comment by juank-pa** [comment] 2017-09-04 14:05
This is expected behavior and the way Local Notifications work. If you need to show a message when the event is triggered you should listen for the `NotificationEvent. NOTIFICATION_ACTION` event and display the corresponding custom made view (MovieClip/Sprite).

**Comment by ukmunnithan** [comment] 2017-09-12 10:46
Hello,
Thanks for the reply.
If we display the message in flex using NotificationEvent. NOTIFICATION_ACTION event.But it will not show the notification in the notification tray of the device.We need to display in both places..
In the app and Notification tray..

Please help

**Comment by juank-pa** [comment] 2017-09-26 23:01
Sadly I think that is by design.

> If the application is foremost and visible when the system delivers the notification, no alert is shown, no icon is badged, and no sound is played. However, the application:didReceiveLocalNotification: is called if the application delegate implements it. The UILocalNotification instance is passed into this method, and the delegate can check its properties or access any custom data from the userInfo dictionary.

This applies to the tray too.

**Comment by juank-pa** [comment] 2017-09-26 23:15
This seems to be supported now in iOS 10 qith the new API but this ANE uses the older API and migrating it will take time.

**Comment by juank-pa** [comment] 2017-11-21 02:01
@ukmunnithan I implemented notifications to appear in the foreground for iOS 10 and later. This is still in an alpha stage along with some other features. If you want to give them a try you're more than welcome. And if you find things not working as desired or suggestion for new features I'll gladly accept them.

**Comment by ukmunnithan** [comment] 2017-11-21 10:03
@juank-pa Thank you for the quick update.I am very happy about your fast response and quick solution that you are providing.I tested the latest ane in my project.Unfortunatelly the notification is not showing if app is running in forground.We are getting the notification received event.But notification is not showing as either overlay or in notification center

**Comment by juank-pa** [comment] 2017-11-21 10:35
Many things changed since that time, so let me be sure you are using the latest version. You probable noticed that since version 1.0.5 I do not include the binary with the repo anymore. Instead I include it as a downloadable from the [release page](https://github.com/juank-pa/JKLocalNotifications-ANE/releases). Also notice that the latest version in master is the latest stable version but not the alpha one. To get the alpha version, got to this [link](https://github.com/juank-pa/JKLocalNotifications-ANE/releases/tag/v1.1.0-alpha.3) and download the ANE in there.

Once downloaded and included in your project. Showing the notification in the foreground is optional. You have to set `Notification.showInForeground` to `true`.

Now that you mention your requirement. I did took care of the notification appearing in the foreground, but never checked if it was appearing in the notification center. If it doesn't appear there this is something made by design that might not be able to change. Let's hope it works for that case.

**Comment by ukmunnithan** [comment] 2017-11-21 10:48
I used the same ane v1.1.0-alpha.3 from the link that you provided.But I didnot set Notification.showInForeground to true.Now I set these value and working good..
Thank you. I will update if I found anything from my side
Also Its showing in Notification centre too

**Comment by ukmunnithan** [comment] 2017-11-21 12:39
@juank-pa Could you please share the updated Flex library file to compile the ANE.
The current file doesn't have the showInForeground.

**Comment by juank-pa** [comment] 2017-11-25 03:40
@ukmunnithan Sadly I do not maintain the Flex library anymore. The ANE is now being compiled using the command line. This way I do not depend on having Flash Builder to do it. The only requirement is the AIR SDK, and of course XCode for the iOS version and Android Studio for the android version.

**Comment by juank-pa** [comment] 2017-12-15 11:26
Happy to announce the new version v1.1.0 came out of alpha and will temporarily hit beta to allow fixing bugs. You are invited to test it out and provide feedback. And don't forget to watch 
![image](https://user-images.githubusercontent.com/5060527/34040097-3d776100-e160-11e7-965f-0f7d36c22402.png) the repo to get information on new versions and features. New features include: support for sounds on Android, custom action buttons in notifications, Android heads up notifications, and more. Thanks in advance.
